### PR TITLE
Create For_while_loop

### PR DESCRIPTION
**Pull request by Anushka0912**
This code can be used to describe for loop and while loop

### CODE REVIEW

**Comment by komal7141** [comment]
Save your file with .c extension so the color will appear.
Place braces at appropriate position.

**Comment by Anushka0912** [comment]
I have committed the change as you have said. Please check it. If you have some more suggestions then please let me know.

**Comment by komal7141** [comment]
There should be no space between dot(.) and c again save your file with .c extension

**Comment by Anushka0912** [comment]
I have committed the change. Thank you

**Pull request merged**
